# Generated by Django 5.2.17 on 2026-09-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('peruana', 'Peruana'), ('italiana', 'Italiana'), ('japonesa', 'Japonesa'), ('mexicana', 'Mexicana'), ('parrilla', 'Parrilla / Carnes'), ('marisqueria', 'Marisquería'), ('vegetariana', 'Vegetariana'), ('cafeteria', 'Cafetería'), ('fusion', 'Fusión')], max_length=20)),
                ('ciudad', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rango_precio', models.CharField(choices=[('$', 'Económico'), ('$$', 'Moderado'), ('$$$', 'Alto'), ('$$$$', 'Premium')], default='$$', max_length=4)),
                ('calificacion', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('capacidad', models.PositiveIntegerField(default=40)),
                ('hora_apertura', models.TimeField(default='12:00')),
                ('hora_cierre', models.TimeField(default='22:00')),
                ('imagen_url', models.URLField()),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-destacado', '-calificacion'],
            },
        ),
    ]
