# Generated by Django 5.2.17 on 2026-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='categoria',
            field=models.CharField(choices=[('paraguaya', 'Comida Paraguaya'), ('parrilla', 'Parrilla y Asado'), ('internacional', 'Internacional'), ('mariscos', 'Mariscos y Pescados'), ('vegetariana', 'Vegetariana'), ('italiana', 'Italiana'), ('japonesa', 'Japonesa'), ('cafeteria', 'Cafetería y Confitería')], max_length=20),
        ),
    ]
