# Generated by Django 5.2.7 on 2025-10-02 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Usado en URLs amigables.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('imagen_logo', models.ImageField(blank=True, null=True, upload_to='restaurantes/logos/')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='restaurantes/portadas/')),
                ('horario_apertura', models.TimeField(help_text='Formato HH:MM')),
                ('horario_cierre', models.TimeField(help_text='Formato HH:MM')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el restaurante está disponible para reservas.')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo de personas que puede sentar la mesa.')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Terraza, Salón principal, Jardín', max_length=100)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='Restaurantes.restaurante')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['restaurante', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='RestauranteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contacto', models.EmailField(blank=True, help_text='Email específico para administración del restaurante.', max_length=254)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('restaurante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='Restaurantes.restaurante')),
            ],
            options={
                'verbose_name': 'Administrador de Restaurante',
                'verbose_name_plural': 'Administradores de Restaurantes',
            },
        ),
    ]
